[project]
name = "sps-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yunji-p", email = "yp2788@columbia.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "en-core-web-md",
    "fastapi[standard]>=0.141.1",
    "spacy>=3.8.16",
]

[tool.uv.sources]
en-core-web-md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl" }

